kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: knative-ci-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: knative-ci
  namespace: default
roleRef:
  kind: Role
  name: knative-ci
  apiGroup: rbac.authorization.k8s.io
