kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: knative-ci
rules:
  - apiGroups: ["build.knative.dev"]
    resources: ["buildtemplates", "builds"]
    verbs: ["get", "create", "update"]
